### ISSUE TITLE
Replace all texts with english inside project includes README

### ISSUE THREAD

**Issue by enesacikoglu** [jkazama/ddd-java#17]
Hello,

Please replace all texts with English to understand easily.
In my opinion, opensource projects can not be in mother language.

Thanks
Enes

**Comment by jkazama** [comment]
Thank you for your feedback.
It seems that more people are watching than I expected, so I would like to consider making it English.

The following practical sample provides an English version, so please refer to it if you like.

https://github.com/jkazama/sample-boot-hibernate/tree/en

**Comment by jkazama** [comment]
I made an English branch for the time being. I'm wondering if this will be my master in the future.

> Because the target domain is assumed to be Japan, I do not know whether it is valid globally.
